from crypto_pandas.binance.binance_spot_client import BinanceSpotClient

client = BinanceSpotClient()
trades = client.get_api_depth(symbol="BTCUSDT")
print(trades)
trades = client.get_api_trades(symbol="BTCUSDT")
print(trades)
trades = client.get_api_historical_trades(symbol="BTCUSDT")
print(trades)
trades = client.get_api_agg_trades(symbol="BTCUSDT")
print(trades)
trades = client.get_api_klines(symbol="BTCUSDT", interval="8h")
print(trades)
trades = client.get_api_ui_klines(symbol="BTCUSDT", interval="8h")
print(trades)
trades = client.get_api_avg_price(symbol="BTCUSDT")
print(trades)
trades = client.get_api_ticker_24hr()
print(trades)
